### ISSUE TITLE
train crack315

### ISSUE THREAD

**Issue by GFDD-insulator** [yakhyo/crackseg#3]
When I used this code to train on the public dataset crack315, dice_ Sorce is close to 0.9999, but the predicted output image has a full black background. What is the problem，can U help me 
![image](https://github.com/yakhyo/crack-segmentation/assets/67264004/cbd85929-0357-4c44-86b6-1e1edd698161)
![image](https://github.com/yakhyo/crack-segmentation/assets/67264004/0d8377c8-2bf3-4b7b-bcd0-2e88639654d8)

**Comment by yakhyo** [comment]
Hi @houruixiang-1024 ,

Thanks for your interest to this repo. I think it probably happens when preparing the labels in dataset. 
[here](https://github.com/yakhyo/crack-segmentation/blob/caff265029910c5e179fe74139163dd70a6fffb4/crackseg/utils/dataset.py#L37C1-L39C41) in `dataset.py` file.

```
if (np.asarray(mask) > 1).any():
    mask = np.asarray(np.asarray(mask) / 255, dtype=np.byte)
    mask = Image.fromarray(mask)
```
Please check the pixel values for your masks and use appropriate normalization in terms of the values. I hope it should solve the issue. If it doesn't then I will test it on my own.

**Comment by yakhyo** [comment]
Hi @houruixiang-1024 

Thanks for your interest to this repo. The inference code in this repo only generates the image masks, which normally has black background and other segmented classes with their appropriate pixel color. 

The code worked as it was intended. I do not exactly see any unexpected behavior of the code. If you have any other questions feel free to ask.
